version: "3.3"
services:
  db:
    container_name: mysql_inventory
    image: mysql:oracle
    env_file:
      - .env
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
  app:
    container_name: fastapi_inventory
    build: .
    restart: always
    env_file:
      - .env
    ports:
      - "9001:9001"
